name: star_news_app_repeat2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  logger: 1.2.2
  gap: 2.0.1
  skeletons: 0.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true

